
line-length = 119

[lint]
ignore = [
    # LineTooLong
    "E501",
    # DoNotAssignLambda
    "E731",
]

select = ["E", "F", "W"]

[lint.per-file-ignores]
# Ignore `E402` (import violations) in all examples
"examples/**" = ["E402"]
