
line-length = 119

[lint]
# Skip `E731` (do not assign a lambda expression, use a def)
ignore = ["E731"]

select = ["E4", "E7", "E9", "F", "W"]

[lint.per-file-ignores]
# Ignore `E402` (import violations) in all examples
"examples/**" = ["E402"]
